### ISSUE TITLE
Move Pali language resources to Therava repo

### ISSUE THREAD

**Issue by kareniel** [johnjago/awesome-theravada#3]
I think we should move the content of [my repo](https://github.com/unbinding-org/awesome-pali) into this awesome list. I'm not really maintaining it and I do believe that the primary value of learning more about Pāli is deeper understanding of Dhamma. 

What do you think?

**Comment by johnjago** [comment]
If you think it's a good idea, then let's do it. I have some free time the next few days, so let me know if you are busy; I can add the items. Or feel free to open a PR.

Just the other day I found [Pali Tutor](https://arrowriver.ca/pali/paliDrill1.html), a website where you can practice conjugations and declensions, and I am sure I will find more great resources. I will be maintaining this list for quite a while since it is listed on Sindre's main awesome list.
